# Database Credentials
db.driverName=com.mysql.cj.jdbc.Driver
db.connectionString=jdbc:mysql://nozomi.proxy.rlwy.net:54200/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=oHpTWGsKBzlxkDvtynTaVRJtjzfmyTGj

# Mailer Credentials
mailer.email = princekumar13810@gmail.com 
mailer.password = voyk nwjp sxhp lgge